### ISSUE TITLE
Running a BP node for Testnet 說明文件有錯

### ISSUE THREAD

**Issue by kimx** [dexon-foundation/wiki#2]
此篇文章的第一步產生NodeKey的命令多了一個"**冒號**"
https://github.com/dexon-foundation/wiki/wiki/Running--a-BP-node-for-Testnet
![command-error](https://user-images.githubusercontent.com/5724118/54796142-008dc680-4c8a-11e9-959b-5dc4c4ca7859.png)

**Comment by aitjcize** [comment]
這在 Linux 上是正確的。
